name: Docker Container Tests

on:
  workflow_run:
    workflows: ["Run Pytest on Push to Main"]
    types:
      - completed
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        working-directory: ./python
        run: |
          docker build -t news-assistant:test .
          docker images
          
      - name: Test container with mock credentials
        run: |
          docker run -d --name news-test -p 3000:3000 \
            -e NEWSAPI_API_KEY=test-key \
            -e OPENAI_API_KEY=test-key \
            -e TEMPERATURE=0.7 \
            -e PORT=3000 \
            news-assistant:test
          
          sleep 5
          docker ps
          docker logs news-test 

      - name: Verify container is running
        run: |
          for i in {1..5}; do
            if docker ps | grep -q news-test && ! docker ps | grep -q "Exited"; then
              echo "Container is running!"
              exit 0
            fi
            echo "Waiting for container..."
            sleep 5
          done
          echo "Container failed to start properly"
          docker logs news-test
          exit 1 