name: Docker Container Tests

on:
  workflow_run:
    workflows: ["Run Pytest on Push to Main"]
    types:
      - completed
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        working-directory: ./python
        run: |
          docker build -t news-assistant:test .
          docker images
          
      - name: Test container with mock credentials
        run: |
          docker run -d --name news-test -p 3000:3000 \
            -e NEWSAPI_API_KEY=test-key \
            -e OPENAI_API_KEY=test-key \
            -e TEMPERATURE=0.7 \
            news-assistant:test
          
          # Give the container time to start
          sleep 5
          
          # Check if container is running
          docker ps
          
          # Check container logs for any startup errors
          docker logs news-test 